# - src: https://github.com/idi-ops/ansible-facts
#   name: facts
# - src: https://github.com/idi-ops/ansible-nodejs
#   name: nodejs
- src: https://github.com/idi-ops/ansible-parsoid
  version: v0.6.1
  name: parsoid
